# frozen_string_literal: true

source 'https://rubygems.org'

gem 'aws-sdk-cloudformation'
gem 'aws-sdk-iam'
gem 'aws-sdk-s3'
gem 'cfndsl', '~>0.16.5'
gem 'colorize'
gem 'rake'
gem 'rubocop'
gem 'yamllint'
